---
# Override resource name
#nameOverride

# Override url base path. Default to mutate
#basePathOverride:

# PodNodesSelector   
# Override podnodeselector handler path. Default to pod-nodes-selector
#podNodesSelectorPathOverride: 
# Confiruation for podnodesselector. The namespace and labels are set here following the format:
#   namespace: key=label,key=label; namespace2: key=label
# Note: Multiple namespaces seperate by ;
#
# Examples:
#   devel: node-role.kubernetes.io/development=true, beta.kubernetes.io/instance-type=t3.large
podNodesSelectorConfig: 
  p-9j5rd-pipeline: env=pipelines
  
service:
  # the service is important. It forms part of the CN for SSL certificate. 
  name: admission-webhook
  #type: 
  annotations: {}

replicas: 1  

strategy: 
  type: RollingUpdate

image: liangrog/admission-webhook-server
imageTag: latest
imagePullPolicy: Always 
